name: commits_list_ui_material
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  commits_list_presentation:
    path: ../commits_list_presentation
  core_arch_flutter:
    path: ../../../core_arch_flutter
  feature_commits_list_api:
    path: ../feature_commits_list_api
  flutter:
    sdk: flutter
  scrollable_positioned_list: 0.2.0-nullsafety.0
  tile:
    path: ../../../tile
  tile_flutter:
    path: ../../../tile_flutter

dev_dependencies:
  diff_lint_rules:
    path: ../../../diff_lint_rules

flutter: