name: app

publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  feature_commits_table_api:
    path: ../feature/commits_table/feature_commits_table_api
  feature_commits_table_impl:
    path: ../feature/commits_table/feature_commits_table_impl
  feature_repos_list_api:
    path: ../feature/repos_list/feature_repos_list_api
  feature_repos_list_impl:
    path: ../feature/repos_list/feature_repos_list_impl
  feature_workspace_api:
    path: ../feature/workspace/feature_workspace_api
  feature_workspace_impl:
    path: ../feature/workspace/feature_workspace_impl
  flutter:
    sdk: flutter
  jugger:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jugger
      ref: 02cb9197b758cd89457d71c2b4c1daab4d92477c

dev_dependencies:
  build_runner: 2.1.1
  diff_lint_rules:
    path: ../diff_lint_rules
  jugger_generator:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jugger_generator
      ref: 2351119ad514db2c2ffbe286677e91936c39ee61

flutter:
  uses-material-design: true