name: feature_repos_list_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  core_arch_flutter:
    path: ../../../core_arch_flutter
  feature_repos_list_api:
    path: ../feature_repos_list_api
  flutter:
    sdk: flutter
  jugger:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jugger
      ref: 02cb9197b758cd89457d71c2b4c1daab4d92477c
  repos_list_domain:
    path: ../repos_list_domain
  repos_list_presentation:
    path: ../repos_list_presentation
  repos_list_ui_material:
    path: ../repos_list_ui_material
  tile_flutter:
    path: ../../../tile_flutter

dev_dependencies:
  build_runner: 2.1.1
  diff_lint_rules:
    path: ../../../diff_lint_rules
  jugger_generator:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jugger_generator
      ref: 2351119ad514db2c2ffbe286677e91936c39ee61