name: feature_repos_list_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  feature_repos_list_api:
    path: ../feature_repos_list_api
  flutter:
    sdk: flutter
  repos_list_ui_material:
    path: ../repos_list_ui_material

dev_dependencies:
  diff_lint_rules:
    path: ../../../diff_lint_rules

flutter: