name: diff
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  app:
    path: ../app
  flutter:
    sdk: flutter

dev_dependencies:
  diff_lint_rules:
    path: ../diff_lint_rules

flutter:
  uses-material-design: true