name: feature_commits_table_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  commits_table_ui_material:
    path: ../commits_table_ui_material
  feature_commits_table_api:
    path: ../feature_commits_table_api
  flutter:
    sdk: flutter

dev_dependencies:
  diff_lint_rules:
    path: ../../../diff_lint_rules

flutter: