name: commits_list_presentation
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  core_arch:
    path: ../../../core_arch

dev_dependencies:
  diff_lint_rules:
    path: ../../../diff_lint_rules

flutter: