name: feature_workspace_impl
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  feature_commits_list_api:
    path: ../../commits_list/feature_commits_list_api
  feature_repos_list_api:
    path: ../../repos_list/feature_repos_list_api
  feature_workspace_api:
    path: ../feature_workspace_api
  flutter:
    sdk: flutter
  workspace_presentation:
    path: ../workspace_presentation
  workspace_ui_material:
    path: ../workspace_ui_material

dev_dependencies:
  diff_lint_rules:
    path: ../../../diff_lint_rules

flutter: