name: repos_list_presentation
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  core_arch:
    path: ../../../core_arch
  freezed_annotation: 0.14.3
  repos_list_domain:
    path: ../repos_list_domain
  tile:
    path: ../../../tile

dev_dependencies:
  build_runner: 2.1.1
  diff_lint_rules:
    path: ../../../diff_lint_rules
  freezed: 0.14.3